name: Run Python Script

on:
  schedule:
    - cron: '*/5 * * * *'  # هر 5 دقیقه
  workflow_dispatch:        # امکان اجرای دستی

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install requests

      - name: Run script and save as index.html
        run: |
          python .github/workflows/Request.py
          mv output.html index.html  # تغییر نام فایل خروجی به index.html

      - name: Commit index.html if changed
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add index.html
          git diff --staged --quiet || git commit -m "Update index.html"
          git push || echo "No changes to push"
